### PR TITLE
add scan sub for "samples"

### PR DESCRIPTION
**Pull request by black-ghost-off**
Add scan sub folders from "samples" to get all sample projects in zephyr

fix for: https://github.com/mylonics/zephyr-ide/issues/7

### CODE REVIEW

**Comment by rijesha** [comment]
Thanks for the PR.
To make this feature complete, could you clean up the list being generated.
Having the full path displayed is not useful. Instead use the label field to display the project name, and the description field to display the path. The path should be a relative path from the sample directory.

So ideally the quick pick list would look like this:
blinky basic
beacon bluetooth
nrfx boards/nrf

You will also need to enable the [matchOnDescription](https://code.visualstudio.com/api/references/vscode-api#QuickPick)  for the quickpick.

**Comment by rijesha** [comment]
The list would also be fine with:

**blinky** _basic/blinky_
**beacon** _bluetooth/beacon_
**nrfx** _boards/nrf/nrfx_

**Comment by rijesha** [comment]
The new commit is not working correctly. You are missing a subdirectory.
i.e _boards/nrf/nrfx_ is showing up as nrf/nrfx

**Comment by black-ghost-off** [comment]
I think it's more correct the way I did it, because accordingly this path is in the documentation (https://docs.zephyrproject.org/latest/samples/boards/nrf/nrfx/README.html) and this path that I did has the same placement in the zephyr repository if necessary

**Comment by black-ghost-off** [comment]
Oh wait, let me che

**Comment by black-ghost-off** [comment]
image
Check on your side again

**Comment by rijesha** [comment]
windows

**Comment by black-ghost-off** [comment]
Can you copy samples to your workspace? Is it work well?

**Comment by rijesha** [comment]
It works now. Looks good.

**Pull request merged**
